#!/usr/bin/env python3
"""
CLOUDX QA Audit Agent
Scans Apex classes against CLOUDX standards and scores them using Claude AI.

Usage:
    python qa_audit.py --project C:\\Projects\\DELL-Foundation
    python qa_audit.py --project . --rules qa_rules.yaml --output report.md
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Phase 1: Quick regex-based checks (free, no API cost)
# ---------------------------------------------------------------------------

# Salesforce ID pattern: 15 or 18 alphanumeric chars that look like an ID
SF_ID_PATTERN = re.compile(r"""['"]([a-zA-Z0-9]{15}|[a-zA-Z0-9]{18})['"]""")
# Known prefixes that indicate a real SF ID (common object key prefixes)
SF_ID_PREFIXES = {
    "001", "003", "005", "006", "00D", "00e", "00G", "00N", "00Q", "00T",
    "00U", "012", "01I", "01p", "01Q", "01s", "01t", "02i", "02s", "03d",
    "04t", "0SO",
}

SOQL_KEYWORDS = re.compile(
    r"\b(SELECT\s+.+?\s+FROM\s+\w+)", re.IGNORECASE | re.DOTALL
)
DML_KEYWORDS = re.compile(
    r"\b(insert|update|delete|upsert|undelete|merge)\s+", re.IGNORECASE
)
LOOP_PATTERN = re.compile(r"\b(for\s*\(|while\s*\()", re.IGNORECASE)


def load_rules(rules_path: str | None) -> dict:
    """Load QA rules from YAML file or return defaults."""
    if rules_path and Path(rules_path).exists():
        with open(rules_path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    # Check for qa_rules.yaml next to this script
    default_path = Path(__file__).parent / "qa_rules.yaml"
    if default_path.exists():
        with open(default_path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    # Fallback: all rules enabled
    return {
        "rules": {
            "with_sharing": {"enabled": True, "severity": "critical"},
            "soql_limit": {"enabled": True, "severity": "warning"},
            "no_soql_in_loops": {"enabled": True, "severity": "critical"},
            "no_hardcoded_ids": {"enabled": True, "severity": "critical"},
            "recursion_guards": {"enabled": True, "severity": "warning"},
            "test_class_exists": {"enabled": True, "severity": "critical"},
            "try_catch_callouts": {"enabled": True, "severity": "warning"},
            "no_magic_numbers": {"enabled": True, "severity": "info"},
            "database_partial_dml": {"enabled": True, "severity": "info"},
            "aura_enabled_cacheable": {"enabled": True, "severity": "info"},
        },
        "scoring": {
            "model": "claude-haiku-4-5",
            "skip_test_classes": True,
            "skip_generated": True,
        },
        "exclude_files": [],
    }


def find_apex_files(project_path: str) -> list[Path]:
    """Find all .cls files in the project."""
    root = Path(project_path)
    cls_files = sorted(root.rglob("force-app/**/*.cls"))
    # Exclude -meta.xml companion files
    return [f for f in cls_files if not f.name.endswith("-meta.xml")]


def is_test_class(file_path: Path, content: str) -> bool:
    """Check if a file is a test class."""
    name = file_path.stem
    if name.endswith("_Test") or name.endswith("Test"):
        return True
    if "@isTest" in content or "@IsTest" in content:
        return True
    return False


def is_generated_class(content: str) -> bool:
    """Check if a class appears auto-generated."""
    indicators = ["// Generated by", "auto-generated", "DO NOT EDIT"]
    return any(ind.lower() in content.lower() for ind in indicators)


def rule_enabled(rules: dict, rule_name: str) -> bool:
    """Check if a specific rule is enabled."""
    return rules.get("rules", {}).get(rule_name, {}).get("enabled", True)


def check_with_sharing(content: str) -> dict:
    """Check if class uses 'with sharing'."""
    # Match class declaration
    class_decl = re.search(
        r"(public|global|private)\s+(virtual\s+|abstract\s+)?"
        r"(with sharing|without sharing|inherited sharing)?\s*class\s+",
        content,
    )
    if not class_decl:
        return {"pass": True, "detail": "No class declaration found (interface/enum?)"}
    sharing = class_decl.group(3)
    if sharing and "with sharing" in sharing:
        return {"pass": True, "detail": "Uses 'with sharing'"}
    if sharing and "without sharing" in sharing:
        return {"pass": False, "detail": "Uses 'without sharing' — needs justification", "severity": "critical"}
    if sharing and "inherited sharing" in sharing:
        return {"pass": True, "detail": "Uses 'inherited sharing'"}
    return {"pass": False, "detail": "No sharing keyword specified", "severity": "critical"}


def check_soql_limit(content: str) -> dict:
    """Check if SOQL queries include LIMIT."""
    queries = SOQL_KEYWORDS.findall(content)
    if not queries:
        return {"pass": True, "detail": "No SOQL queries found"}
    missing_limit = []
    for i, q in enumerate(queries, 1):
        if "LIMIT" not in q.upper() and "limit" not in q:
            missing_limit.append(f"Query #{i}")
    if missing_limit:
        return {
            "pass": False,
            "detail": f"SOQL without LIMIT: {', '.join(missing_limit)}",
            "severity": "warning",
        }
    return {"pass": True, "detail": f"All {len(queries)} queries have LIMIT"}


def check_soql_in_loops(content: str) -> dict:
    """Check for SOQL/DML inside loops (basic heuristic)."""
    lines = content.split("\n")
    loop_depth = 0
    issues = []
    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        # Track loop depth (simplified)
        if LOOP_PATTERN.search(stripped):
            loop_depth += 1
        if loop_depth > 0:
            if re.search(r"\bDatabase\.\w+\(", stripped) or DML_KEYWORDS.search(stripped):
                issues.append(f"Line {i}: DML in loop")
            if re.search(r"\[.*SELECT.*FROM", stripped, re.IGNORECASE):
                issues.append(f"Line {i}: SOQL in loop")
        # Approximate loop end by counting braces
        open_braces = stripped.count("{")
        close_braces = stripped.count("}")
        loop_depth = max(0, loop_depth + open_braces - close_braces)
    if issues:
        return {"pass": False, "detail": "; ".join(issues[:5]), "severity": "critical"}
    return {"pass": True, "detail": "No SOQL/DML in loops detected"}


def check_hardcoded_ids(content: str) -> dict:
    """Check for hardcoded Salesforce IDs."""
    matches = SF_ID_PATTERN.findall(content)
    suspicious = []
    for m in matches:
        prefix = m[:3]
        if prefix in SF_ID_PREFIXES:
            suspicious.append(m[:8] + "...")
    if suspicious:
        return {
            "pass": False,
            "detail": f"Possible hardcoded IDs: {', '.join(suspicious[:3])}",
            "severity": "critical",
        }
    return {"pass": True, "detail": "No hardcoded IDs detected"}


def check_recursion_guards(content: str, file_path: Path) -> dict:
    """Check if handler classes have recursion prevention."""
    name = file_path.stem.lower()
    is_handler = "handler" in name or "trigger" in name
    if not is_handler:
        return {"pass": True, "detail": "Not a handler class — skipped"}
    if "isRunning" in content or "isExecuting" in content or "alreadyRun" in content:
        return {"pass": True, "detail": "Recursion guard found"}
    return {
        "pass": False,
        "detail": "Handler without recursion guard (isRunning pattern)",
        "severity": "warning",
    }


def check_test_class_exists(
    file_path: Path, all_files: list[Path], content: str
) -> dict:
    """Check if a corresponding test class exists."""
    if is_test_class(file_path, content):
        return {"pass": True, "detail": "This IS a test class"}
    name = file_path.stem
    possible_test_names = {f"{name}_Test", f"{name}Test"}
    all_names = {f.stem for f in all_files}
    found = possible_test_names & all_names
    if found:
        return {"pass": True, "detail": f"Test class: {found.pop()}.cls"}
    return {
        "pass": False,
        "detail": f"No test class found (expected {name}_Test.cls)",
        "severity": "critical",
    }


def check_try_catch_callouts(content: str) -> dict:
    """Check if HTTP callouts are wrapped in try-catch."""
    has_callout = bool(
        re.search(r"(HttpRequest|Http\.send|callout:)", content, re.IGNORECASE)
    )
    if not has_callout:
        return {"pass": True, "detail": "No callouts found"}
    has_try_catch = "try" in content and "catch" in content
    if has_try_catch:
        return {"pass": True, "detail": "Callouts wrapped in try-catch"}
    return {
        "pass": False,
        "detail": "HTTP callout without try-catch",
        "severity": "warning",
    }


def run_quick_checks(
    file_path: Path, content: str, rules: dict, all_files: list[Path]
) -> dict:
    """Run all regex-based quick checks on a single file."""
    results = {}
    is_test = is_test_class(file_path, content)
    exempt = {"pass": True, "detail": "Test class — exempt"}

    checks = {
        "with_sharing": lambda: exempt if is_test else check_with_sharing(content),
        "soql_limit": lambda: exempt if is_test else check_soql_limit(content),
        "no_soql_in_loops": lambda: exempt if is_test else check_soql_in_loops(content),
        "no_hardcoded_ids": lambda: check_hardcoded_ids(content),
        "recursion_guards": lambda: exempt if is_test else check_recursion_guards(content, file_path),
        "test_class_exists": lambda: check_test_class_exists(
            file_path, all_files, content
        ),
        "try_catch_callouts": lambda: exempt if is_test else check_try_catch_callouts(content),
    }
    for rule_name, check_fn in checks.items():
        if rule_enabled(rules, rule_name):
            results[rule_name] = check_fn()
    return results


# ---------------------------------------------------------------------------
# Phase 2: AI-powered deep analysis (Claude Haiku)
# ---------------------------------------------------------------------------

SCORING_PROMPT = """You are a Salesforce Apex code reviewer for CLOUDX, an Israeli Salesforce consulting company.

Score this Apex class against the CLOUDX 150-point Apex Quality Rubric:

| Category | Max Points | What to Check |
|---|---|---|
| Governor Limits | 25 | No SOQL/DML in loops, bulkified triggers, collection-based operations |
| Security | 25 | WITH SECURITY_ENFORCED or stripInaccessible, no SOQL injection, no hardcoded IDs |
| Testing | 25 | Test class exists, coverage potential, bulk test patterns, no seeAllData |
| Error Handling | 20 | Try-catch on DML/callouts, meaningful messages, no empty catches, logging |
| Code Quality | 20 | Single Responsibility, method <40 lines, meaningful names, no magic numbers |
| Performance | 20 | Selective SOQL, Maps for lookups, async for heavy processing |
| Maintainability | 15 | Handler pattern, separation of concerns, Custom Metadata for config |

Respond ONLY with valid JSON (no markdown, no backticks):
{
    "scores": {
        "governor_limits": { "score": 0, "max": 25, "findings": ["..."] },
        "security": { "score": 0, "max": 25, "findings": ["..."] },
        "testing": { "score": 0, "max": 25, "findings": ["..."] },
        "error_handling": { "score": 0, "max": 20, "findings": ["..."] },
        "code_quality": { "score": 0, "max": 20, "findings": ["..."] },
        "performance": { "score": 0, "max": 20, "findings": ["..."] },
        "maintainability": { "score": 0, "max": 15, "findings": ["..."] }
    },
    "total_score": 0,
    "grade": "Excellent|Good|Fair|Problematic|Critical",
    "top_issues": ["issue 1", "issue 2", "issue 3"],
    "suggestions": ["suggestion 1", "suggestion 2"]
}"""


def analyze_with_ai(client, file_path: Path, content: str, model: str) -> dict | None:
    """Send file to Claude for deep analysis and scoring."""
    try:
        response = client.messages.create(
            model=model,
            max_tokens=2048,
            messages=[
                {
                    "role": "user",
                    "content": f"{SCORING_PROMPT}\n\n"
                    f"## File: {file_path.name}\n\n```apex\n{content}\n```",
                }
            ],
        )
        text = response.content[0].text.strip()
        # Try to parse JSON from response
        return json.loads(text)
    except json.JSONDecodeError:
        # Try to extract JSON from markdown code block
        match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                pass
        return None
    except Exception as e:
        print(f"  ⚠ AI analysis failed for {file_path.name}: {e}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Phase 3: Report generation
# ---------------------------------------------------------------------------

GRADE_THRESHOLDS = [
    (130, "Excellent"),
    (105, "Good"),
    (80, "Fair"),
    (55, "Problematic"),
    (0, "Critical"),
]


def score_to_grade(score: int) -> str:
    for threshold, grade in GRADE_THRESHOLDS:
        if score >= threshold:
            return grade
    return "Critical"


def severity_icon(severity: str) -> str:
    return {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(severity, "⚪")


def generate_report(
    quick_results: dict,
    ai_results: dict,
    project_name: str,
) -> str:
    """Generate a Markdown report from scan results."""
    lines = []
    lines.append(f"# QA Audit Report — {project_name}")
    lines.append("")
    lines.append(f"**Generated by**: CLOUDX QA Audit Agent")
    lines.append(f"**Files scanned**: {len(quick_results)}")
    lines.append("")

    # --- Summary table ---
    lines.append("## Summary")
    lines.append("")
    lines.append("| File | Quick Check | AI Score | Grade |")
    lines.append("|------|-----------|----------|-------|")

    total_score = 0
    scored_count = 0
    grade_counts = {"Excellent": 0, "Good": 0, "Fair": 0, "Problematic": 0, "Critical": 0}
    all_issues = []

    for file_path, checks in sorted(quick_results.items()):
        name = Path(file_path).stem
        fails = sum(1 for c in checks.values() if not c.get("pass", True))
        total_checks = len(checks)
        quick_status = f"{total_checks - fails}/{total_checks} passed"

        ai = ai_results.get(file_path)
        if ai:
            ai_score = ai.get("total_score", 0)
            grade = ai.get("grade", score_to_grade(ai_score))
            total_score += ai_score
            scored_count += 1
            grade_counts[grade] = grade_counts.get(grade, 0) + 1
            all_issues.extend(ai.get("top_issues", []))
            lines.append(f"| {name} | {quick_status} | {ai_score}/150 | {grade} |")
        else:
            lines.append(f"| {name} | {quick_status} | — | — |")

    avg_score = total_score / scored_count if scored_count else 0
    avg_grade = score_to_grade(int(avg_score))

    lines.append("")
    if scored_count > 0:
        lines.append(f"**Average score**: {avg_score:.0f}/150 ({avg_grade})")
        lines.append("")
        dist = " | ".join(f"{g}: {c}" for g, c in grade_counts.items() if c > 0)
        lines.append(f"**Grade distribution**: {dist}")
        lines.append("")

    # --- Top recurring issues ---
    if all_issues:
        # Count issue frequency
        issue_freq = {}
        for issue in all_issues:
            issue_freq[issue] = issue_freq.get(issue, 0) + 1
        top_issues = sorted(issue_freq.items(), key=lambda x: -x[1])[:5]
        lines.append("## Top Recurring Issues")
        lines.append("")
        for issue, count in top_issues:
            lines.append(f"- {issue} ({count}x)")
        lines.append("")

    # --- Per-file details ---
    lines.append("## Details per File")
    lines.append("")

    for file_path, checks in sorted(quick_results.items()):
        name = Path(file_path).stem
        lines.append(f"### {name}")
        lines.append("")

        # Quick checks
        lines.append("**Quick Checks:**")
        lines.append("")
        for rule_name, result in checks.items():
            icon = "✅" if result.get("pass") else severity_icon(
                result.get("severity", "info")
            )
            lines.append(f"- {icon} **{rule_name}**: {result.get('detail', '')}")
        lines.append("")

        # AI analysis
        ai = ai_results.get(file_path)
        if ai and "scores" in ai:
            lines.append("**AI Scoring (150 pts):**")
            lines.append("")
            lines.append("| Category | Score | Findings |")
            lines.append("|----------|-------|----------|")
            for cat, data in ai["scores"].items():
                score = data.get("score", 0)
                max_pts = data.get("max", 0)
                findings = "; ".join(data.get("findings", [])[:2])
                lines.append(
                    f"| {cat.replace('_', ' ').title()} | {score}/{max_pts} | {findings} |"
                )
            lines.append("")
            if ai.get("suggestions"):
                lines.append("**Suggestions:**")
                for s in ai["suggestions"][:3]:
                    lines.append(f"- {s}")
                lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="CLOUDX QA Audit Agent — Scan Apex code against CLOUDX standards"
    )
    parser.add_argument(
        "--project", required=True, help="Path to Salesforce project root"
    )
    parser.add_argument(
        "--rules", default=None, help="Path to qa_rules.yaml (default: auto-detect)"
    )
    parser.add_argument(
        "--output", default=None, help="Output file path (default: stdout)"
    )
    parser.add_argument(
        "--quick-only",
        action="store_true",
        help="Skip AI analysis, run regex checks only (free)",
    )
    args = parser.parse_args()

    # Load config
    rules = load_rules(args.rules)
    scoring_config = rules.get("scoring", {})
    model = scoring_config.get("model", "claude-haiku-4-5")
    exclude = set(rules.get("exclude_files", []))

    # Find Apex files
    apex_files = find_apex_files(args.project)
    if not apex_files:
        print("No Apex files found in", args.project, file=sys.stderr)
        sys.exit(1)

    project_name = Path(args.project).resolve().name
    print(f"=== CLOUDX QA Audit: {project_name} ===", file=sys.stderr)
    print(f"Found {len(apex_files)} Apex files", file=sys.stderr)

    # Phase 1: Quick checks
    print("\n[Phase 1] Running quick checks...", file=sys.stderr)
    quick_results = {}
    all_files = apex_files  # For test class lookup
    for f in apex_files:
        if f.name in exclude:
            continue
        content = f.read_text(encoding="utf-8", errors="replace")
        quick_results[str(f)] = run_quick_checks(f, content, rules, all_files)
        status = "✅" if all(
            v.get("pass", True) for v in quick_results[str(f)].values()
        ) else "⚠"
        print(f"  {status} {f.name}", file=sys.stderr)

    # Phase 2: AI analysis
    ai_results = {}
    if not args.quick_only:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            print(
                "\n⚠ ANTHROPIC_API_KEY not set — skipping AI analysis.",
                file=sys.stderr,
            )
            print("  Set it to enable deep scoring with Claude.", file=sys.stderr)
        else:
            import anthropic

            client = anthropic.Anthropic()
            print(f"\n[Phase 2] AI analysis with {model}...", file=sys.stderr)
            for f in apex_files:
                if f.name in exclude:
                    continue
                content = f.read_text(encoding="utf-8", errors="replace")
                # Skip test classes and generated classes per config
                if scoring_config.get("skip_test_classes") and is_test_class(
                    f, content
                ):
                    continue
                if scoring_config.get("skip_generated") and is_generated_class(content):
                    continue
                print(f"  Analyzing {f.name}...", file=sys.stderr)
                result = analyze_with_ai(client, f, content, model)
                if result:
                    ai_results[str(f)] = result

    # Phase 3: Generate report
    print("\n[Phase 3] Generating report...", file=sys.stderr)
    report = generate_report(quick_results, ai_results, project_name)

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"\n✅ Report saved to {args.output}", file=sys.stderr)
    else:
        sys.stdout.buffer.write(report.encode("utf-8"))
        sys.stdout.buffer.write(b"\n")


if __name__ == "__main__":
    main()
